### PR TITLE
WIP: attempt to support FontAwesome5

### PR DESCRIPTION
**Pull request by chicco785**
Hi @Viglino,
I made an attempt to inject FontAwesome 5. 

- I created a small tool, that allows to generate the definitions from the font-awesome npm libraries
- I update the FontStyle example, but not all  font-awesome icons are rendered... any clue?

Many Thanks

### CODE REVIEW

**Comment by Viglino** [comment]
Do you have a working example ?

**Comment by chicco785** [comment]
> Do you have a working example ?

i updated the `examples/style/map.style.font.html` example, not sure you had in mind something different

**Comment by Viglino** [comment]
I mean an online example to see what's wrong...

**Comment by chicco785** [comment]
> I mean an online example to see what's wrong...

i see, i will try to deploy it somewhere

**Comment by Viglino** [comment]
I've added a new font definition: https://github.com/Viglino/ol-ext/blob/master/dist/extra/FontAwesome5Def.js
You can use it to show FontAwesome5 symbols with a fontStyle: '900'.
See example: https://viglino.github.io/ol-ext/examples/style/map.fontawesome.5.html

**Pull request closed without merging**
