### PR TITLE
Add snapguide support for modify and add flag for initial draw guides

### PR DESCRIPTION
**Pull request by megawac**
ezgif-3-5f75e0c7ce

This adds `snapGuides.setModifyInteraction(olModifyInstance)` support which lets you render snap guides while modifying an existing feature. The guides use the previous 2 verticies and next 2 points as references.

### CODE REVIEW

**Comment by megawac** [comment]
Also I'm currently playing with ways to reduce the length of the guide lines that are generated to more closely mirror the size of the current map (https://github.com/megawac/ol-ext/commit/c7409346a213121a798e2bf80d99347634a467ce)

**Comment by Viglino** [comment]
The length of the guide is defined in the `addGuide`  function that limit the editing extent (`var extent`).
The extent is a buffer around the current map extent. 
This is a 1^5 buffer or 100 x the current extent for small zoom (ie. large extent):
````javascript
extent = ol_extent_buffer(extent, Math.max (1e5+1, (extent[2]-extent[0])*100));
````
The 1e5 factor could be a parameter or a more accurate value depending on the current extent (based on a zoom factor).
I also tried to split the guide in smaller segments but the snapping will snap to segment's points and not to the line itself...
This will also depend on the nature of the guide: a local guide for edition associated with an object or a global guide (to snap to a meridian or a specific coordinate) the user expects to be available on the whole map.

**Comment by megawac** [comment]
Yeah, the `1e5` buffer needs to be based on the projection as at least in my use case we're using an orthographic projection with extents within a couple square kilometers. In my case the 1e5 value is too large to render any guides.

**Comment by megawac** [comment]
> I also tried to split the guide in smaller segments but the snapping will snap to segment's points and not to the line itself...

Easy fix for this would be to make the line strings use only the first and last points, I'll throw up a PR later today with some tweaks :)

**Pull request merged**
