### PR TITLE
Fix bug when try to modify feature

### PR DESCRIPTION
**Pull request by kirolga**
Hello!
I was faced with bug in example of feature modifying.

Steps to reproduce bug:
- visit http://viglino.github.io/ol-ext/examples/interaction/map.interaction.modifyfeature.html
- choose 'modify' option
- then try to editfeature

### CODE REVIEW

**Comment by Viglino** [comment]
This is a breaking change introduce with ol v6.
Modification must be done in the `interaction/Modify.js` file. 
`ol-ext.js` and `ol-ext.min.js` are recreated on each build using lib files.
I'll try to push a modification asap.
@+

**Comment by kirolga** [comment]
Thank you for your reply.
You are right. I change interaction/Modify.js due to recommendations.
I hope now all is right. :)

**Comment by Viglino** [comment]
The problem is the lib should be compatible with ol <6
- ol<6 use `ol.getUid()`
- ol>=6 use `ol.util.getUid()` (breaking change)

This is only to use with js lib, module version has no issue...
Both function must be imported (actually it is the same, the import name is only to get the ol namespace when build):
```javascript
import {getUid as ol_getUid} from 'ol/util'
import {getUid as ol_util_getUid} from 'ol/util'
```
Then a test must be done when `ol` is defined (non module)
```javascript
    // Openlayers < 6 use ol.getUid
    if (window.ol && window.ol.getUid) featuresById[ol_getUid(feature)] = feature;
    else featuresById[ol_util_getUid(feature)] = feature;
```

NB: this is a hack to get the features concerned by the classic `ol.interaction.Modify`.

**Comment by Viglino** [comment]
I've push a correction see https://github.com/Viglino/ol-ext/commit/658a188d56e99e25c0834087400ea68932e25af2 for details.
Thanks for the feedback!

**Pull request closed without merging**
