### PR TITLE
Fix LayerSwitcher use of ol.extent and DrawRegular use of ol.geom and…

### PR DESCRIPTION
**Pull request by siiinc**
… others

### CODE REVIEW

**Comment by darkscript** [comment]
Thanks for the fix

**Comment by siiinc** [comment]
Any chance of building a new version for npm?

Cheers,

Jerry
________________________________

**Comment by Viglino** [comment]
I'll try tout push à New version à sa
@+

**Comment by siiinc** [comment]
Merci.

________________________________

**Comment by Viglino** [comment]
v2.0.3 is out

**Pull request merged**
