### PR TITLE
FixedPopup: Allows fixing the popup on coordinates

### PR DESCRIPTION
**Pull request by HelloYuiYui**
### Purpose
Allow FixedPopup class to be fixed on map coordinates. Similar to a popup, while retaining the functionality to be moved around on the map. This is an enhancement to the fixed popup. 

### How
A new parameter "fixedPosition" is passed when creating the popup, if set to true it saves the coordinates of the popup and updates pixel position of the popup accordingly when the map is moved so the popup stays on the saved coordinates. 

Also addresses the minor point of options on the example html page not applying to the second popup. (see lines 138 & 141 @ `fixedpopup.html`)

### CODE REVIEW

**Comment by Viglino** [comment]
The FixedPopup class is a subclass of the Popup class that inherits from Ovelays. It override the `updatePixelPosition` and `updateRenderedPosition` from this root class. 
I don't think it's a good practice to hack the subclass to restore the root behavior. You should consider using two instances (one Popup and one FixedPopup) and switch when you need.

**Comment by Viglino** [comment]
I've pushed a commit that just call the root class method (super) when the fixed property is set to false: `ol/Overlay/FixedPopup~setFixed(bool)`

**Comment by Viglino** [comment]
OK I see

**Comment by Viglino** [comment]
I finally get your code but rename the method 'hook' to be more readable.
The popup can be hooked on the 'map' `popup.setHook('map')`  or on the 'viewport' `popup.setHook('viewport')`.
`popup.get('hook')` lets you get it back.
See online: https://viglino.github.io/ol-ext/examples/popup/map.fixedpopup.html

**Comment by HelloYuiYui** [comment]
Nice, thank you! 

Added minor fixes to the options so when they change both open popups are updated. Currently if you have two popup's open (with shift+click) and change the options they are only applied to the first popup.

**Pull request merged**
